import React, { useState, useRef, useEffect, useCallback } from 'react';
import AIChat from './AIChat';
import NotesEditor from './NotesEditor';
import VoiceRecorder from './VoiceRecorder';
import cloudApi from '../cloudApi';
import { getSession } from '../hooks/useClinicSession';
import { isDoctor, isSecretary } from '../utils/roleUtils';
import { useUX } from '../context/UXContext';
import { updateCloudPatient, secretaryCloudWrite } from '../services/patientSyncService';
import '../new-design.css';

function exportPatientPDF(patient, attachments) {
  var fmt = function(v) { return v || '—'; };
  var notes = patient.notes
    ? patient.notes.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    : 'No notes recorded.';
  var attHtml = attachments.length > 0
    ? '<div class="sec"><div class="sec-title">Attachments (' + attachments.length + ')</div>' +
      attachments.map(function(a) { return '<div style="font-size:13px;padding:3px 0">&#128206; ' + a.file_name + '</div>'; }).join('') + '</div>'
    : '';
  var html = '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Patient</title>' +
    '<style>body{font-family:Arial,sans-serif;color:#1e293b;padding:40px;max-width:700px;margin:auto}' +
    'h1{color:#1D9E75;font-size:22px;margin-bottom:4px}.sub{color:#64748b;font-size:13px;margin-bottom:28px}' +
    '.sec{margin-bottom:22px}.sec-title{font-size:11px;text-transform:uppercase;letter-spacing:.06em;color:#94a3b8;margin-bottom:8px}' +
    '.row{display:flex;gap:40px;margin-bottom:8px}.field label{font-size:11px;color:#94a3b8;display:block}' +
    '.field span{font-size:14px;font-weight:500}' +
    '.notes{background:#f8fafc;border-left:3px solid #1D9E75;padding:12px 16px;font-size:13px;line-height:1.6;white-space:pre-wrap;border-radius:4px}' +
    '.footer{margin-top:40px;font-size:11px;color:#94a3b8;border-top:1px solid #e2e8f0;padding-top:12px}</style></head><body>' +
    '<h1>' + fmt(patient.full_name) + '</h1>' +
    '<div class="sub">Patient Record — Exported ' + new Date().toLocaleDateString('en-GB', {day:'2-digit',month:'short',year:'numeric'}) + '</div>' +
    '<div class="sec"><div class="sec-title">Patient Information</div>' +
    '<div class="row"><div class="field"><label>Phone</label><span>' + fmt(patient.phone) + '</span></div>' +
    '<div class="field"><label>Email</label><span>' + fmt(patient.email) + '</span></div></div>' +
    '<div class="row"><div class="field"><label>Status</label><span>' + fmt(patient.status) + '</span></div>' +
    '<div class="field"><label>Appointment</label><span>' + fmt(patient.appointment) + '</span></div></div></div>' +
    '<div class="sec"><div class="sec-title">Notes</div><div class="notes">' + notes + '</div></div>' +
    attHtml + '<div class="footer">Generated by MediDesk AI</div></body></html>';
  var win = window.open('', '_blank');
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(function() { win.print(); }, 400);
}

function buildTimeline(patient, attachments, appointments) {
  var events = [];
  if (patient.created_at) events.push({ date: patient.created_at, label: 'Patient created', icon: '👤' });
  if (patient.updated_at && patient.updated_at !== patient.created_at)
    events.push({ date: patient.updated_at, label: 'Record updated', icon: '📝' });
  (attachments || []).forEach(function(a) {
    if (a.created_at) events.push({ date: a.created_at, label: 'File added: ' + a.file_name, icon: '📎' });
  });
  (appointments || []).forEach(function(a) {
    if (a.created_at) events.push({
      date: a.created_at,
      label: 'Appointment ' + a.status + ' — ' + a.appointment_date + ' ' + a.start_time + '–' + a.end_time,
      icon: '📅',
    });
  });
  return events.sort(function(a, b) { return new Date(b.date) - new Date(a.date); });
}

function fmtDate(iso) {
  if (!iso) return '';
  try { return new Date(iso).toLocaleString('en-GB', { day:'2-digit', month:'short', year:'numeric', hour:'2-digit', minute:'2-digit' }); }
  catch(e) { return iso; }
}

const PatientDetail = ({ selectedPatient, settings, onPatientRefresh }) => {
  const { userRole } = getSession();
  const doctorMode = isDoctor(userRole);
  const secretaryMode = isSecretary(userRole);
  const { showToast, reportSyncIssue } = useUX();
  const [showNotesEditor, setShowNotesEditor] = useState(false);
  const [attachments, setAttachments] = useState([]);
  const [appointments, setAppointments] = useState([]);
  const [uploading, setUploading]   = useState(false);
  const [uploadProgress, setUploadProgress] = useState(0); // 0–100
  const [activeTab, setActiveTab] = useState('overview');
  const [restoring, setRestoring] = useState(false);
  const fileInputRef = useRef(null);

  // Prescription modal state
  const [showPrescription, setShowPrescription] = useState(false);
  const [prescriptionData, setPrescriptionData] = useState(null);
  const [loadingPrescription, setLoadingPrescription] = useState(false);
  const [errorPrescription, setErrorPrescription] = useState('');
  const [clinicInfo, setClinicInfo] = useState({ doctor_name: '', clinic_name: '' });

  // Vertical split state — topHeight is % of the body area
  const [topHeight, setTopHeight] = useState(55);
  const isDragging = useRef(false);
  const bodyRef = useRef(null);

  const onDividerMouseDown = useCallback((e) => {
    e.preventDefault();
    isDragging.current = true;
    const onMove = (ev) => {
      if (!isDragging.current || !bodyRef.current) return;
      const rect = bodyRef.current.getBoundingClientRect();
      const pct = ((ev.clientY - rect.top) / rect.height) * 100;
      setTopHeight(Math.min(80, Math.max(20, pct)));
    };
    const onUp = () => {
      isDragging.current = false;
      window.removeEventListener('mousemove', onMove);
      window.removeEventListener('mouseup', onUp);
    };
    window.addEventListener('mousemove', onMove);
    window.addEventListener('mouseup', onUp);
  }, []);

  useEffect(() => {
    if (selectedPatient) {
      loadAttachments();
      loadAppointments();
      setActiveTab('overview');
    }
  }, [selectedPatient]);

  // Load clinic info once — uses cloud API for both doctor and secretary
  useEffect(() => {
    cloudApi.get('/clinics/me').then(r => {
      if (r.data) setClinicInfo({ doctor_name: r.data.doctor_name, clinic_name: r.data.clinic_name });
    }).catch(() => {}); // silently skip if not available
  }, []);

  const generatePrescription = async () => {
    setShowPrescription(true);
    setLoadingPrescription(true);
    setErrorPrescription('');
    setPrescriptionData(null);
    const prompt = `Generate a professional medical prescription for this patient.
Return STRICT JSON only, no extra text:
{"medications":[{"name":"","dosage":"","duration":""}],"instructions":""}
Patient:
- Name: ${selectedPatient.full_name}
- Status: ${selectedPatient.status || ''}
- Notes: ${selectedPatient.notes || 'none'}`;
    try {
      const res = await cloudApi.post('/chat', { message: prompt, patient_context: selectedPatient });
      const raw = res.data.response || '';
      const match = raw.match(/\{[\s\S]*\}/);
      if (!match) throw new Error('No JSON found in response');
      const parsed = JSON.parse(match[0]);
      if (!Array.isArray(parsed.medications)) throw new Error('Invalid prescription format');
      setPrescriptionData(parsed);
    } catch (e) {
      setErrorPrescription('Could not generate prescription. Try again.');
    } finally {
      setLoadingPrescription(false);
    }
  };

  const printPrescription = () => {
    const today = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' });
    const meds = (prescriptionData?.medications || [])
      .map(m => `<li><strong>${m.name}</strong> — ${m.dosage} — ${m.duration}</li>`).join('');
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Prescription</title>
<style>
  body{font-family:Arial,sans-serif;padding:40px;max-width:600px;margin:auto;color:#1e293b}
  h2{color:#1D9E75;margin-bottom:2px}
  .sub{color:#64748b;font-size:13px;margin-bottom:24px}
  .label{font-size:11px;text-transform:uppercase;color:#94a3b8;letter-spacing:.05em;margin:20px 0 6px}
  ul{padding-left:20px;line-height:2}
  .instructions{background:#f8fafc;border-left:3px solid #1D9E75;padding:10px 14px;font-size:13px;border-radius:4px}
  .sig{margin-top:40px;border-top:1px solid #e2e8f0;padding-top:12px;font-size:12px;color:#94a3b8}
  @media print{body{padding:20px}}
</style></head><body>
<h2>Dr. ${clinicInfo.doctor_name || 'Doctor'}</h2>
<div class="sub">${clinicInfo.clinic_name || 'Clinic'}</div>
<div class="label">Patient</div>
<div>${selectedPatient.full_name}</div>
<div class="label">Date</div>
<div>${today}</div>
<div class="label">Prescription</div>
<ul>${meds}</ul>
<div class="label">Instructions</div>
<div class="instructions">${prescriptionData?.instructions || ''}</div>
<div class="sig">Signature: __________</div>
</body></html>`;
    const w = window.open('', '_blank');
    w.document.write(html);
    w.document.close();
    w.focus();
    setTimeout(() => w.print(), 400);
  };

  const loadAttachments = async () => {
    // Secretary has no local backend — use cloud for both roles
    if (!selectedPatient?.id) { setAttachments([]); return; }
    try {
      const res = await cloudApi.get('/patients/' + selectedPatient.id + '/attachments');
      setAttachments((res.data.attachments || []).filter(a => a && a.file_name));
    } catch(e) { setAttachments([]); }
  };

  const loadAppointments = async () => {
    // Both roles: fetch from cloud using patient name / global_id
    try {
      const res = await cloudApi.get('/appointments');
      const all = res.data.appointments || [];
      setAppointments(all.filter(a =>
        a.patient_name === selectedPatient.full_name ||
        (selectedPatient.global_id && a.patient_global_id === selectedPatient.global_id) ||
        (selectedPatient.id && a.patient_id === selectedPatient.id)
      ));
    } catch(e) { setAppointments([]); }
  };

  const handleTranscriptionComplete = async (transcription) => {
    if (!selectedPatient?.id && !selectedPatient?.global_id) return;
    const newNotes = selectedPatient.notes
      ? selectedPatient.notes + '\n\nVoice: ' + transcription
      : 'Voice: ' + transcription;
    try {
      // Both roles: write to cloud with offline queue fallback
      const cloudResult = await updateCloudPatient({ ...selectedPatient, notes: newNotes });
      if (!cloudResult.ok) {
        if (cloudResult.conflict) {
          showToast(`⚠️ Your note update was not saved because another user updated this patient. Reloading latest version.`, 'error', 8000);
          reportSyncIssue({ type: 'conflict', action: 'update', message: `Patient notes conflict for ${selectedPatient.full_name || 'patient'}.`, patientId: selectedPatient.id });
          if (onPatientRefresh) onPatientRefresh(selectedPatient);
          return;
        }
        showToast('⚠️ Note saved but cloud sync failed. Will retry automatically.', 'error', 8000);
      }
      if (onPatientRefresh) onPatientRefresh({ ...selectedPatient, notes: newNotes });
    } catch(e) { console.error('[PatientDetail] transcription save failed:', e); }
  };

  const handleFileSelect = async (event) => {
    const file = event.target.files[0];
    if (!file || !selectedPatient) return;

    // Validate extension before upload
    const ext = file.name.split('.').pop().toLowerCase();
    const allowed = ['pdf', 'png', 'jpg', 'jpeg', 'gif', 'webp'];
    if (!allowed.includes(ext)) {
      // Inline error — no alert()
      setUploadProgress(-1); // -1 = error state
      setTimeout(() => setUploadProgress(0), 3000);
      return;
    }

    setUploading(true);
    setUploadProgress(0);
    try {
      const fd = new FormData();
      fd.append('file', file);
      
      const uploadWithRetry = async (retries = 3) => {
         try {
            return await cloudApi.post('/patients/' + selectedPatient.id + '/attachments', fd, {
               headers: { 'Content-Type': 'multipart/form-data' },
               onUploadProgress: (e) => {
                 if (e.total) setUploadProgress(Math.round((e.loaded / e.total) * 100));
               },
            });
         } catch (e) {
            if (retries > 0 && !e.response) { // Only retry network errors, not 4xx
               await new Promise(r => setTimeout(r, 1000));
               return uploadWithRetry(retries - 1);
            }
            throw e;
         }
      };
      const res = await uploadWithRetry(3);
      if (res.data.success && res.data.attachment?.file_name) {
        setAttachments(prev => [res.data.attachment, ...prev]);
        setUploadProgress(100);
        setTimeout(() => setUploadProgress(0), 1500);
      }
    } catch(e) {
      setUploadProgress(-1);
      setTimeout(() => setUploadProgress(0), 3000);
    } finally {
      setUploading(false);
      if (fileInputRef.current) fileInputRef.current.value = '';
    }
  };

  const handleDeleteAttachment = async (id) => {
    if (!window.confirm('Delete this file?')) return;
    try {
      await cloudApi.delete('/attachments/' + id);
      setAttachments(prev => prev.filter(a => a.id !== id));
    } catch(e) { alert('Error deleting file'); }
  };

  const handleDownloadAttachment = (att) => {
    if (!att?.url && !att?.id) return;
    // Use presigned URL if available, otherwise fall back to open endpoint
    const url = att.url || (cloudApi.defaults.baseURL + '/attachments/' + att.id + '/open');
    const win = window.open(url, '_blank');
    if (!win) { const l = document.createElement('a'); l.href = url; l.download = att.file_name; document.body.appendChild(l); l.click(); document.body.removeChild(l); }
  };

  const truncate = (name, max = 20) => {
    if (!name || name.length <= max) return name;
    const ext = name.split('.').pop();
    return name.substring(0, max - ext.length - 4) + '...' + ext;
  };

  const handleRestorePatient = async () => {
    if (!selectedPatient?.id) return;
    setRestoring(true);
    try {
      const res = await cloudApi.post(`/patients/${selectedPatient.id}/restore`);
      if (res.data.success) {
        showToast('Patient restored successfully.', 'success');
        if (onPatientRefresh) onPatientRefresh(res.data.patient);
      }
    } catch (e) {
      showToast(e.response?.data?.error || 'Failed to restore patient.', 'error');
    } finally {
      setRestoring(false);
    }
  };

  const getInitials = () => selectedPatient?.full_name?.split(' ').map(w => w[0]).join('').toUpperCase().slice(0, 2) || 'PA';

  if (!selectedPatient) {
    return (
      <div className="right-panel">
        <div className="empty-state">
          <svg className="empty-state-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor">
            <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/>
          </svg>
          <h3>No Patient Selected</h3>
          <p>Select a patient from the table to view their details</p>
        </div>
      </div>
    );
  }

  const timeline = buildTimeline(selectedPatient, attachments, appointments);

  return (
    <div className="right-panel">
      <div className="patient-details">

        {/* Fixed header — shrinks to content */}
        <div style={{ flexShrink: 0 }}>
          <div className="patient-detail-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
            <div className="patient-detail-info">
              <div className="patient-avatar">{getInitials()}</div>
              <div className="patient-name-section">
                <h2 className="patient-name">{selectedPatient.full_name}</h2>
                <p className="patient-phone">{selectedPatient.phone || 'No phone'}</p>
                <div className={`status-badge status-${selectedPatient.status?.toLowerCase()}`}>{selectedPatient.status}</div>
              </div>
            </div>
            <div style={{ display: 'flex', gap: 6, flexShrink: 0, marginTop: 4 }}>
              {/* Restore button — only shown when patient is soft-deleted, doctor only */}
              {doctorMode && selectedPatient.deleted_at && (
                <button
                  onClick={handleRestorePatient}
                  disabled={restoring}
                  style={{
                    padding: '6px 14px', background: restoring ? '#94a3b8' : '#f59e0b',
                    color: '#fff', border: 'none', borderRadius: 6, fontSize: 12,
                    cursor: restoring ? 'not-allowed' : 'pointer', fontWeight: 600,
                  }}
                >
                  {restoring ? 'Restoring...' : '↩ Restore Patient'}
                </button>
              )}
              <button
                onClick={() => exportPatientPDF(selectedPatient, attachments)}
                style={{ padding: '6px 14px', background: '#1D9E75', color: '#fff', border: 'none', borderRadius: 6, fontSize: 12, cursor: 'pointer', fontWeight: 500 }}
              >
                ↓ Export PDF
              </button>
              {doctorMode && (
              <button
                onClick={generatePrescription}
                disabled={loadingPrescription}
                style={{ padding: '6px 14px', background: loadingPrescription ? '#94a3b8' : '#7c3aed', color: '#fff', border: 'none', borderRadius: 6, fontSize: 12, cursor: loadingPrescription ? 'not-allowed' : 'pointer', fontWeight: 500 }}
              >
                {loadingPrescription ? '...' : '💊 Prescription'}
              </button>
              )}
            </div>
          </div>

          <div style={{ display: 'flex', borderBottom: '1px solid #e2e8f0', marginTop: 12 }}>
            {['overview', 'timeline'].map(tab => (
              <button key={tab} onClick={() => setActiveTab(tab)} style={{
                padding: '8px 16px', border: 'none', background: 'none', cursor: 'pointer',
                fontSize: 13, fontWeight: activeTab === tab ? 600 : 400,
                color: activeTab === tab ? '#1D9E75' : '#64748b',
                borderBottom: activeTab === tab ? '2px solid #1D9E75' : '2px solid transparent',
                marginBottom: -1,
              }}>
                {tab === 'overview' ? 'Overview' : 'Timeline'}
              </button>
            ))}
          </div>
        </div>

        {/* Scrollable/resizable body — takes remaining height */}
        {activeTab === 'overview' && (
          <div ref={bodyRef} style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', minHeight: 0 }}>

            {/* Top section — scrollable */}
            <div style={{ height: `${topHeight}%`, overflowY: 'auto', overflowX: 'hidden', minHeight: 0, padding: '12px 0' }}>
              <div className="meta-cards">
                <div className="meta-card">
                  <div className="meta-card-label">Appointment</div>
                  <div className="meta-card-value">{selectedPatient.appointment || 'Not scheduled'}</div>
                </div>
                <div className="meta-card">
                  <div className="meta-card-label">Files</div>
                  <div className="meta-card-value">{attachments.length} files</div>
                </div>
              </div>

              <div className="notes-preview">
                <div className="section-label">Notes</div>
                <div className="notes-content">
                  {selectedPatient.notes
                    ? (selectedPatient.notes.length > 150 ? selectedPatient.notes.substring(0, 150) + '...' : selectedPatient.notes)
                    : 'No notes available'}
                </div>
                <button className="open-editor-btn" onClick={() => setShowNotesEditor(true)}>Open editor →</button>
              </div>

              <div className="voice-recording-section">
                <div className="section-label">Voice Recording</div>
                {secretaryMode ? (
                  <p style={{ fontSize: 12, color: '#94a3b8', margin: '4px 0' }}>
                    Voice recording requires the local backend (doctor only).
                  </p>
                ) : (
                  <VoiceRecorder onTranscriptionComplete={handleTranscriptionComplete} placeholder="Record voice notes for this patient" />
                )}
              </div>

              <div className="attachments">
                <div className="section-label">Attachments</div>

                {/* Upload progress bar */}
                {uploading && uploadProgress >= 0 && (
                  <div style={{ margin: '4px 0 8px', background: '#e2e8f0', borderRadius: 4, height: 6, overflow: 'hidden' }}>
                    <div style={{
                      height: '100%', borderRadius: 4, transition: 'width 0.2s',
                      background: uploadProgress === 100 ? '#10b981' : '#1D9E75',
                      width: `${uploadProgress}%`,
                    }} />
                  </div>
                )}
                {uploadProgress === -1 && (
                  <p style={{ fontSize: 12, color: '#dc2626', margin: '0 0 6px' }}>
                    Upload failed. Allowed types: PDF, PNG, JPG, JPEG, GIF, WebP (max 25MB).
                  </p>
                )}

                <div className="attachments-row">
                  {attachments.map(att => (
                    <div key={att.id} className="file-pill" onClick={() => handleDownloadAttachment(att)} title={att.file_name}>
                      <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                        <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z"/>
                        <polyline points="14,2 14,8 20,8"/>
                      </svg>
                      <span>{truncate(att.file_name)}</span>
                      <button className="file-delete-btn" onClick={e => { e.stopPropagation(); handleDeleteAttachment(att.id); }}>×</button>
                    </div>
                  ))}
                  {!secretaryMode && (
                    <button
                      className="add-file-btn"
                      onClick={() => fileInputRef.current?.click()}
                      disabled={uploading}
                      style={{ opacity: uploading ? 0.5 : 1, cursor: uploading ? 'not-allowed' : 'pointer' }}
                    >
                      {uploading ? `Uploading ${uploadProgress}%...` : '+ Add file'}
                    </button>
                  )}
                  {secretaryMode && attachments.length === 0 && (
                    <p style={{ fontSize: 12, color: '#94a3b8', margin: '4px 0' }}>
                      File attachments are only available on the doctor's computer.
                    </p>
                  )}
                </div>
                <input ref={fileInputRef} type="file" accept=".pdf,.png,.jpg,.jpeg,.gif,.webp" onChange={handleFileSelect} style={{ display: 'none' }} />
              </div>
            </div>

            {/* Drag divider */}
            <div
              onMouseDown={onDividerMouseDown}
              style={{
                height: 6, background: '#e2e8f0', cursor: 'row-resize', flexShrink: 0,
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                transition: 'background 0.2s',
              }}
              onMouseEnter={e => e.currentTarget.style.background = '#3b82f6'}
              onMouseLeave={e => e.currentTarget.style.background = '#e2e8f0'}
            >
              <div style={{ width: 32, height: 2, background: '#94a3b8', borderRadius: 2 }} />
            </div>

            {/* Bottom section — AI Chat (doctor only) */}
            <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', minHeight: 0 }}>
              {doctorMode
                ? <AIChat patient={selectedPatient} />
                : (
                  <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#94a3b8', fontSize: 13, flexDirection: 'column', gap: 6 }}>
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
                      <rect x="3" y="11" width="18" height="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/>
                    </svg>
                    AI Chat is available for doctors only
                  </div>
                )
              }
            </div>

          </div>
        )}

        {activeTab === 'timeline' && (
          <div style={{ flex: 1, overflowY: 'auto', padding: '12px 0 4px' }}>
            {timeline.length === 0 ? (
              <div style={{ textAlign: 'center', color: '#94a3b8', padding: '40px 0', fontSize: 13 }}>No activity yet</div>
            ) : (
              <div style={{ position: 'relative', paddingLeft: 32 }}>
                <div style={{ position: 'absolute', left: 12, top: 0, bottom: 0, width: 2, background: '#e2e8f0' }} />
                {timeline.map((ev, i) => (
                  <div key={i} style={{ position: 'relative', marginBottom: 20 }}>
                    <div style={{
                      position: 'absolute', left: -24, top: 0, width: 22, height: 22, borderRadius: '50%',
                      background: '#f8fafc', border: '2px solid #e2e8f0',
                      display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 11,
                    }}>{ev.icon}</div>
                    <div style={{ fontSize: 13, fontWeight: 500, color: '#1e293b', lineHeight: 1.4 }}>{ev.label}</div>
                    <div style={{ fontSize: 11, color: '#94a3b8', marginTop: 2 }}>{fmtDate(ev.date)}</div>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

      </div>

      {showNotesEditor && (
        <NotesEditor patient={selectedPatient} onClose={() => setShowNotesEditor(false)} onSave={() => setShowNotesEditor(false)} />
      )}

      {/* Prescription Modal — doctor only */}
      {showPrescription && doctorMode && (
        <div style={{
          position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.45)', zIndex: 1000,
          display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20,
        }}>
          <div style={{
            background: '#fff', borderRadius: 12, width: '100%', maxWidth: 560,
            maxHeight: '90vh', display: 'flex', flexDirection: 'column',
            boxShadow: '0 20px 60px rgba(0,0,0,0.2)',
          }}>
            {/* Modal header */}
            <div style={{ padding: '16px 20px', borderBottom: '1px solid #e2e8f0', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <span style={{ fontWeight: 600, fontSize: 15, color: '#1e293b' }}>💊 Generate Prescription</span>
              <button onClick={() => setShowPrescription(false)} style={{ background: 'none', border: 'none', fontSize: 18, cursor: 'pointer', color: '#94a3b8' }}>×</button>
            </div>

            {/* Modal body */}
            <div style={{ flex: 1, overflowY: 'auto', padding: '20px' }}>
              {loadingPrescription && (
                <div style={{ textAlign: 'center', padding: '40px 0', color: '#64748b' }}>
                  <div style={{ width: 32, height: 32, border: '3px solid #e2e8f0', borderTop: '3px solid #7c3aed', borderRadius: '50%', animation: 'spin 1s linear infinite', margin: '0 auto 12px' }} />
                  Generating prescription...
                </div>
              )}

              {errorPrescription && (
                <div style={{ background: '#fef2f2', border: '1px solid #fecaca', borderRadius: 8, padding: '12px 16px', color: '#dc2626', fontSize: 13 }}>
                  {errorPrescription}
                </div>
              )}

              {prescriptionData && !loadingPrescription && (
                <div id="prescription-content" style={{ fontFamily: 'Arial, sans-serif', color: '#1e293b' }}>
                  <div style={{ marginBottom: 4, fontSize: 16, fontWeight: 700, color: '#1D9E75' }}>
                    Dr. {clinicInfo.doctor_name || 'Doctor'}
                  </div>
                  <div style={{ fontSize: 12, color: '#64748b', marginBottom: 20 }}>{clinicInfo.clinic_name || 'Clinic'}</div>

                  <div style={{ display: 'flex', gap: 32, marginBottom: 20 }}>
                    <div>
                      <div style={{ fontSize: 10, textTransform: 'uppercase', color: '#94a3b8', letterSpacing: '0.05em', marginBottom: 3 }}>Patient</div>
                      <div style={{ fontSize: 13, fontWeight: 500 }}>{selectedPatient.full_name}</div>
                    </div>
                    <div>
                      <div style={{ fontSize: 10, textTransform: 'uppercase', color: '#94a3b8', letterSpacing: '0.05em', marginBottom: 3 }}>Date</div>
                      <div style={{ fontSize: 13, fontWeight: 500 }}>{new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })}</div>
                    </div>
                  </div>

                  {/* Editable medications */}
                  <div style={{ fontSize: 10, textTransform: 'uppercase', color: '#94a3b8', letterSpacing: '0.05em', marginBottom: 8 }}>Prescription</div>
                  <div style={{ marginBottom: 4 }}>
                    {prescriptionData.medications.map((m, i) => (
                      <div key={i} style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr auto', gap: 6, marginBottom: 6, alignItems: 'center' }}>
                        <input
                          value={m.name}
                          onChange={e => setPrescriptionData(prev => ({ ...prev, medications: prev.medications.map((x, j) => j === i ? { ...x, name: e.target.value } : x) }))}
                          placeholder="Medication"
                          style={{ padding: '6px 10px', border: '1px solid #e2e8f0', borderRadius: 6, fontSize: 12, outline: 'none', background: '#f8fafc' }}
                        />
                        <input
                          value={m.dosage}
                          onChange={e => setPrescriptionData(prev => ({ ...prev, medications: prev.medications.map((x, j) => j === i ? { ...x, dosage: e.target.value } : x) }))}
                          placeholder="Dosage"
                          style={{ padding: '6px 10px', border: '1px solid #e2e8f0', borderRadius: 6, fontSize: 12, outline: 'none', background: '#f8fafc' }}
                        />
                        <input
                          value={m.duration}
                          onChange={e => setPrescriptionData(prev => ({ ...prev, medications: prev.medications.map((x, j) => j === i ? { ...x, duration: e.target.value } : x) }))}
                          placeholder="Duration"
                          style={{ padding: '6px 10px', border: '1px solid #e2e8f0', borderRadius: 6, fontSize: 12, outline: 'none', background: '#f8fafc' }}
                        />
                        <button
                          onClick={() => setPrescriptionData(prev => ({ ...prev, medications: prev.medications.filter((_, j) => j !== i) }))}
                          style={{ padding: '4px 8px', background: 'none', border: '1px solid #fecaca', borderRadius: 6, color: '#ef4444', cursor: 'pointer', fontSize: 12 }}
                        >×</button>
                      </div>
                    ))}
                    <button
                      onClick={() => setPrescriptionData(prev => ({ ...prev, medications: [...prev.medications, { name: '', dosage: '', duration: '' }] }))}
                      style={{ padding: '5px 12px', background: 'none', border: '1px dashed #7c3aed', borderRadius: 6, color: '#7c3aed', cursor: 'pointer', fontSize: 12, marginTop: 2 }}
                    >+ Add medication</button>
                  </div>

                  {/* Editable instructions */}
                  <div style={{ fontSize: 10, textTransform: 'uppercase', color: '#94a3b8', letterSpacing: '0.05em', margin: '16px 0 8px' }}>Instructions</div>
                  <textarea
                    value={prescriptionData.instructions}
                    onChange={e => setPrescriptionData(prev => ({ ...prev, instructions: e.target.value }))}
                    rows={3}
                    style={{ width: '100%', padding: '10px 14px', border: '1px solid #e2e8f0', borderLeft: '3px solid #1D9E75', borderRadius: 4, fontSize: 13, lineHeight: 1.6, resize: 'vertical', outline: 'none', background: '#f8fafc', fontFamily: 'inherit', boxSizing: 'border-box' }}
                  />

                  <div style={{ borderTop: '1px solid #e2e8f0', paddingTop: 12, marginTop: 16, fontSize: 11, color: '#94a3b8' }}>
                    Signature: __________
                  </div>
                </div>
              )}
            </div>

            {/* Modal footer */}
            <div style={{ padding: '12px 20px', borderTop: '1px solid #e2e8f0', display: 'flex', gap: 8, justifyContent: 'flex-end' }}>
              {prescriptionData && !loadingPrescription && (
                <>
                  <button onClick={printPrescription} style={{ padding: '7px 14px', background: '#1D9E75', color: '#fff', border: 'none', borderRadius: 6, fontSize: 12, cursor: 'pointer', fontWeight: 500 }}>
                    🖨 Print / Save PDF
                  </button>
                  <button onClick={generatePrescription} style={{ padding: '7px 14px', background: '#f1f5f9', color: '#475569', border: 'none', borderRadius: 6, fontSize: 12, cursor: 'pointer', fontWeight: 500 }}>
                    ↺ Regenerate
                  </button>
                </>
              )}
              <button onClick={() => setShowPrescription(false)} style={{ padding: '7px 14px', background: '#f1f5f9', color: '#475569', border: 'none', borderRadius: 6, fontSize: 12, cursor: 'pointer', fontWeight: 500 }}>
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default PatientDetail;
